#!/bin/bash
echo -n "Sisesta reisijate arv bussis: "
read reisijate_arv
echo -n "Seisesta kohtade arv bussis: "
read kohtade_arv
maha_j22nud=`expr $reisijate_arv - $kohtade_arv`
echo  $maha_j22nud
echo -n "Jäi maha 
"

